name: Ironclad Password Manager Tests

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - main


jobs:
  test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: maven


      - name: Run tests
        run: mvn test

      - name: Build project
        run: mvn package -DskipTests